version: '3.5'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 54q4r4_r007
    volumes:
      - ./all-collections.archive:/all-collections.archive

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 54q4r4_r007
      ME_CONFIG_MONGODB_URL: mongodb://root:54q4r4_r007@mongo:27017/

  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: 54q4r4-api
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URI=${DATABASE_URI}
    ports:
      - ${API_PORT}:3000
    depends_on:
      - mongo
    volumes:
      - ./api/src:/app/src
      - ./api/test:/app/test

  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: 54q4r4-client
    environment:
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:${API_PORT}
      - NEXT_PUBLIC_SERVER_API_URL=http://api:3000
      - NEXTAUTH_SECRET=secret
    ports:
      - ${CLIENT_PORT}:3000
    depends_on:
      - api
    volumes:
      - ./client/src:/app/src
